spring:
  redis:
    host: hillewaere-poc.redis.cache.windows.net
    port: 6380
    ssl: true
    password: wpKshnHMGrsbgKOR9YSexe5BpdXXS0pP9AzCaCP1GDQ=
    timeout: 5s
  cache:
    type: redis
    redis:
      time-to-live: 86400000